$Env:PROGRAMATIC_EXPOSE_PORT = 8000
$Env:PROGRAMATIC_SERVICE_NAME = "programatic"
$Env:PROGRAMATIC__SERVICE_INSTANCE_ID = "programatic-instance-1"
$Env:PROGRAMATIC_OTLP_ENDPOINT = "http://localhost:4317"
$Env:OTEL_PYTHON_LOG_CORRELATION = "true"
$Env:OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED = "true"
python programatic.py